// frontend-ng/src/app/layouts/main-layout.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router, NavigationEnd } from '@angular/router';
import {
    LucideAngularModule,
    LayoutDashboard,
    Building2,
    Users,
    FileText,
    CreditCard,
    Wrench,
    BarChart3,
    Settings,
    ChevronLeft,
    ChevronRight,
    LogOut,
    HandCoins
} from 'lucide-angular';
import { filter } from 'rxjs/operators';

@Component({
    selector: 'app-main-layout',
    standalone: true,
    imports: [CommonModule, RouterModule, LucideAngularModule],
    templateUrl: './main-layout.component.html',
    styleUrls: ['./main-layout.component.css']
})
export class MainLayoutComponent implements OnInit, OnDestroy {
    collapsed = false;
    currentPath = '';
    userRole = 'dg';
    userLabel = 'Direction Générale';

    readonly LayoutDashboard = LayoutDashboard;
    readonly Building2 = Building2;
    readonly Users = Users;
    readonly FileText = FileText;
    readonly CreditCard = CreditCard;
    readonly Wrench = Wrench;
    readonly BarChart3 = BarChart3;
    readonly Settings = Settings;
    readonly ChevronLeft = ChevronLeft;
    readonly ChevronRight = ChevronRight;
    readonly LogOut = LogOut;
    readonly HandCoins = HandCoins;

    menuItems = [
        { icon: LayoutDashboard, label: 'Tableau de bord', href: '/dashboard' },
        { icon: HandCoins, label: 'Recouvrement', href: '/recouvrement' },
        { icon: Building2, label: 'Résidences', href: '/residences' },
        { icon: Users, label: 'Copropriétaires', href: '/coproprietaires' },
        { icon: FileText, label: 'Réclamations', href: '/reclamations' },
        { icon: CreditCard, label: 'Finance & Recouvrement', href: '/finance' },
        { icon: Wrench, label: 'Prestataires', href: '/prestataires' },
        { icon: BarChart3, label: 'Reporting & KPIs', href: '/reporting' },
        { icon: Settings, label: 'Paramètres', href: '/parametres' },
    ];

    constructor(private router: Router) {
        this.router.events.pipe(
            filter(event => event instanceof NavigationEnd)
        ).subscribe((event: any) => {
            this.currentPath = event.urlAfterRedirects;
        });
    }

    ngOnInit() {
        this.userRole = localStorage.getItem('user_role') || 'dg';
        this.userLabel = this.userRole === 'dg' ? 'Direction Générale' : 'Gestionnaire Recouvrement';

        // Filter menu items for Recouvrement role
        if (this.userRole === 'recouvrement') {
            this.menuItems = [
                { icon: HandCoins, label: 'Recouvrement', href: '/recouvrement' },
                { icon: FileText, label: 'Réclamations', href: '/reclamations' },
                { icon: CreditCard, label: 'Finance', href: '/finance' },
            ];
        }

        this.checkAuth();
        this.handleResize();
        window.addEventListener('resize', () => this.handleResize());
    }

    ngOnDestroy() {
        window.removeEventListener('resize', () => this.handleResize());
    }

    checkAuth() {
        const token = localStorage.getItem('syndic_token');
        if (!token && !this.router.url.includes('/login')) {
            // this.router.navigate(['/login']); // Commented out for now to allow development without full login
        }
    }

    handleResize() {
        this.collapsed = window.innerWidth < 1024;
    }

    toggleSidebar() {
        this.collapsed = !this.collapsed;
    }

    logout() {
        localStorage.removeItem('syndic_token');
        localStorage.removeItem('user_role');
        this.router.navigate(['/login']);
    }

    isActive(href: string): boolean {
        return this.currentPath.startsWith(href);
    }
}

<div class="flex h-screen bg-gray-50">
    <!-- Sidebar -->
    <aside class="flex flex-col border-r border-gray-800 bg-[#0f0f1a] text-white transition-all duration-300"
        [ngClass]="collapsed ? 'w-[60px]' : 'w-[260px]'">
        <div class="flex h-16 items-center px-4 py-4" [ngClass]="collapsed ? 'justify-center' : 'justify-between'">
            <div *ngIf="!collapsed" class="flex items-center gap-2 font-bold text-xl">
                <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-600 text-white">
                    <lucide-icon [name]="Building2" class="h-5 w-5"></lucide-icon>
                </div>
                <span class="bg-gradient-to-r from-blue-400 to-blue-200 bg-clip-text text-transparent">SyndicPro</span>
            </div>
            <div *ngIf="collapsed" class="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-600 text-white">
                <lucide-icon [name]="Building2" class="h-5 w-5"></lucide-icon>
            </div>

            <button *ngIf="!collapsed" (click)="toggleSidebar()"
                class="rounded-full bg-gray-800 p-1.5 text-gray-400 hover:bg-gray-700 hover:text-white">
                <lucide-icon [name]="ChevronLeft" class="h-4 w-4"></lucide-icon>
            </button>
        </div>

        <div *ngIf="collapsed" class="flex justify-center pb-2">
            <button (click)="toggleSidebar()"
                class="rounded-full bg-gray-800 p-1.5 text-gray-400 hover:bg-gray-700 hover:text-white">
                <lucide-icon [name]="ChevronRight" class="h-4 w-4"></lucide-icon>
            </button>
        </div>

        <nav class="flex-1 space-y-1 overflow-y-auto px-2 py-4 custom-scrollbar">
            <a *ngFor="let item of menuItems" [routerLink]="item.href" routerLinkActive="bg-blue-600 text-white"
                [routerLinkActiveOptions]="{exact: true}"
                class="flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium transition-colors text-gray-400 hover:bg-white/10 hover:text-white"
                [ngClass]="{'justify-center px-2': collapsed}" [title]="collapsed ? item.label : ''">
                <lucide-icon [name]="item.icon" class="h-5 w-5 shrink-0"></lucide-icon>
                <span *ngIf="!collapsed">{{item.label}}</span>
            </a>
        </nav>

        <div class="border-t border-gray-800 p-4">
            <div class="flex items-center gap-3" [ngClass]="collapsed ? 'justify-center' : ''">
                <div
                    class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-blue-900 text-blue-200 ring-2 ring-blue-900/50">
                    <span class="font-semibold">N</span>
                </div>
                <div *ngIf="!collapsed" class="overflow-hidden">
                    <p class="truncate text-sm font-medium text-white">{{userLabel}}</p>
                    <p class="truncate text-xs text-gray-400">v2.4.1</p>
                </div>
            </div>
            <button (click)="logout()"
                class="mt-4 flex w-full items-center gap-2 rounded-lg py-2 text-sm font-medium text-red-400 transition-colors hover:bg-red-950/30 hover:text-red-300"
                [ngClass]="collapsed ? 'justify-center' : 'px-2'" [title]="collapsed ? 'Déconnexion' : ''">
                <lucide-icon [name]="LogOut" class="h-5 w-5 shrink-0"></lucide-icon>
                <span *ngIf="!collapsed">Déconnexion</span>
            </button>
        </div>
    </aside>

    <!-- Mobile Toggle Button -->
    <button
        class="fixed bottom-6 right-6 z-50 flex h-14 w-14 items-center justify-center rounded-full bg-blue-600 text-white shadow-xl lg:hidden hover:bg-blue-700 transition-colors"
        (click)="toggleSidebar()">
        <lucide-icon [name]="collapsed ? ChevronRight : ChevronLeft" class="h-6 w-6"></lucide-icon>
    </button>

    <!-- Main Content -->
    <main class="flex-1 overflow-y-auto bg-[#f8f9fa]">
        <router-outlet></router-outlet>
    </main>
</div>

// frontend/src/layouts/MainLayout.tsx
import { useState, useEffect } from "react";
import { Outlet, useLocation, useNavigate } from "react-router-dom";
import {
    CreditCard, LayoutDashboard, Building2, Users, FileText, Wrench, BarChart3, Settings,
    ChevronLeft, ChevronRight, LogOut
} from "lucide-react";
import { cn } from "../lib/utils";

interface SidebarItemProps {
    icon: any;
    label: string;
    href: string;
    active: boolean;
    collapsed: boolean;
}

const SidebarItem = ({ icon: Icon, label, href, active, collapsed }: SidebarItemProps) => {
    const navigate = useNavigate();
    return (
        <button
            onClick={() => navigate(href)}
            className={cn(
                "flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium transition-colors",
                active
                    ? "bg-blue-600 text-white"
                    : "text-gray-400 hover:bg-white/10 hover:text-white",
                collapsed && "justify-center px-2"
            )}
            title={collapsed ? label : undefined}
        >
            <Icon className="h-5 w-5 shrink-0" />
            {!collapsed && <span>{label}</span>}
        </button>
    );
};

export default function MainLayout() {
    const [collapsed, setCollapsed] = useState(false);
    const location = useLocation();
    const navigate = useNavigate();

    useEffect(() => {
        const token = localStorage.getItem("syndic_token");
        if (!token) {
            navigate("/login");
        }
    }, [navigate]);

    const handleLogout = () => {
        localStorage.removeItem("syndic_token");
        navigate("/login");
    };


    // Mobile Responsive: Auto-collapse on small screens
    useEffect(() => {
        const handleResize = () => {
            if (window.innerWidth < 1024) {
                setCollapsed(true);
            } else {
                setCollapsed(false);
            }
        };

        // Initial check
        handleResize();

        window.addEventListener("resize", handleResize);
        return () => window.removeEventListener("resize", handleResize);
    }, []);

    const menuItems = [
        { icon: LayoutDashboard, label: "Tableau de bord", href: "/dashboard" },
        { icon: Building2, label: "Résidences", href: "/residences" },
        { icon: Users, label: "Copropriétaires", href: "/coproprietaires" },
        { icon: FileText, label: "Réclamations", href: "/reclamations" },
        { icon: CreditCard, label: "Finance & Recouvrement", href: "/finance" },
        { icon: Wrench, label: "Prestataires", href: "/prestataires" },
        { icon: BarChart3, label: "Reporting & KPIs", href: "/reporting" },
        { icon: Settings, label: "Paramètres", href: "/parametres" },
    ];

    return (
        <div className="flex h-screen bg-gray-50">
            {/* Sidebar */}
            <aside
                className={cn(
                    "flex flex-col border-r border-gray-800 bg-[#0f0f1a] text-white transition-all duration-300",
                    collapsed ? "w-[60px]" : "w-[260px]"
                )}
            >
                <div className={cn("flex h-16 items-center px-4 py-4", collapsed ? "justify-center" : "justify-between")}>
                    {!collapsed && (
                        <div className="flex items-center gap-2 font-bold text-xl">
                            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-600 text-white">
                                <Building2 className="h-5 w-5" />
                            </div>
                            <span className="bg-gradient-to-r from-blue-400 to-blue-200 bg-clip-text text-transparent">SyndicPro</span>
                        </div>
                    )}
                    {collapsed && (
                        <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-600 text-white">
                            <Building2 className="h-5 w-5" />
                        </div>
                    )}
                    {!collapsed && (
                        <button
                            onClick={() => setCollapsed(!collapsed)}
                            className="rounded-full bg-gray-800 p-1.5 text-gray-400 hover:bg-gray-700 hover:text-white"
                        >
                            <ChevronLeft className="h-4 w-4" />
                        </button>
                    )}
                </div>

                {collapsed && (
                    <div className="flex justify-center pb-2">
                        <button
                            onClick={() => setCollapsed(!collapsed)}
                            className="rounded-full bg-gray-800 p-1.5 text-gray-400 hover:bg-gray-700 hover:text-white"
                        >
                            <ChevronRight className="h-4 w-4" />
                        </button>
                    </div>
                )}

                <nav className="flex-1 space-y-1 overflow-y-auto px-2 py-4 custom-scrollbar">
                    {menuItems.map((item) => (
                        <SidebarItem
                            key={item.href}
                            {...item}
                            active={location.pathname === item.href}
                            collapsed={collapsed}
                        />
                    ))}
                </nav>

                <div className="border-t border-gray-800 p-4">
                    <div className={cn("flex items-center gap-3", collapsed && "justify-center")}>
                        <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-blue-900 text-blue-200 ring-2 ring-blue-900/50">
                            <span className="font-semibold">N</span>
                        </div>
                        {!collapsed && (
                            <div className="overflow-hidden">
                                <p className="truncate text-sm font-medium text-white">Direction Générale</p>
                                <p className="truncate text-xs text-gray-400">v2.4.1</p>
                            </div>
                        )}
                    </div>
                    <button
                        onClick={handleLogout}
                        className={cn(
                            "mt-4 flex w-full items-center gap-2 rounded-lg py-2 text-sm font-medium text-red-400 transition-colors hover:bg-red-950/30 hover:text-red-300",
                            collapsed ? "justify-center" : "px-2"
                        )}
                        title={collapsed ? "Déconnexion" : undefined}
                    >
                        <LogOut className="h-5 w-5 shrink-0" />
                        {!collapsed && <span>Déconnexion</span>}
                    </button>
                </div>
            </aside>

            {/* Mobile Toggle Button (Visible only on small screens) */}
            <button
                className="fixed bottom-6 right-6 z-50 flex h-14 w-14 items-center justify-center rounded-full bg-blue-600 text-white shadow-xl lg:hidden hover:bg-blue-700 transition-colors"
                onClick={() => setCollapsed(!collapsed)}
            >
                {collapsed ? <ChevronRight className="h-6 w-6" /> : <ChevronLeft className="h-6 w-6" />}
            </button>

            {/* Main Content */}
            <main className="flex-1 overflow-y-auto bg-[#f8f9fa]">
                <Outlet />
            </main>
        </div>
    );
}
